### ISSUE TITLE
The page has some basic CSS

### ISSUE THREAD

**Issue by aymarc** [gi-azubi/htmlassignment#2]
The image we are meant to draw our inspiration actually has some basic styling while we are told in the instructions that the page is designed purely in Html and should also use Html only.  I don't think anyone could actually get the result on the image unless he fails to follow the instruction. 
Some of the stylings I believe the page has are as follow:
    - The title, subtitle, and the paragraph tag have a text-align value of center.
    - The background-color is not the default.

**Comment by Ozanjitech** [comment]
if you add border in the html it goner work for you

**Comment by Ozanjitech** [comment]
that is not a css style
